target: model.clip_distill.ControlLDM
params:
  # parameterization: x0
  linear_start: 0.00085
  linear_end: 0.0120
  num_timesteps_cond: 1
  log_every_t: 200
  timesteps: 1000
  first_stage_key: "jpg"
  cond_stage_key: "clip_img"
  control_key: "hint"
  image_size: 64
  channels: 4
  cond_stage_trainable: True
  conditioning_key: crossattn
  monitor: val/loss_simple_ema
  scale_factor: 0.18215
  use_ema: False
  ignore_keys: ['preprocess_model']
  
  sd_locked: True
  only_mid_control: False
  # Learning rate.
  learning_rate: 1e-4
  use_cfg: False
  l_latent_weight: 0.
  l_clip_weight: 1.

  scheduler_config: # 10000 warmup steps
    target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
    params:
      warm_up_steps: 1000
      lr_min: 1e-2
      lr_max: 1
      lr_start: 1e-2
      max_decay_steps: 100001

  control_stage_config:
    target: model.clip_distill.ControlNet
    params:
      use_checkpoint: True
      image_size: 32 # unused
      in_channels: 4
      hint_channels: 4
      model_channels: 320
      attention_resolutions: [ 4, 2, 1 ]
      num_res_blocks: 2
      channel_mult: [ 1, 2, 4, 4 ]
      num_head_channels: 64 # need to fix for flash-attn
      use_spatial_transformer: True
      use_linear_in_transformer: True
      transformer_depth: 1
      context_dim: 1024
      legacy: False
      decoder_channels: []

  unet_config:
    target: model.clip_distill.ControlledUnetModel
    params:
      use_checkpoint: True
      image_size: 32 # unused
      in_channels: 4
      out_channels: 4
      model_channels: 320
      attention_resolutions: [ 4, 2, 1 ]
      num_res_blocks: 2
      channel_mult: [ 1, 2, 4, 4 ]
      num_head_channels: 64 # need to fix for flash-attn
      use_spatial_transformer: True
      use_linear_in_transformer: True
      transformer_depth: 1
      context_dim: 1024
      legacy: False

  first_stage_config:
    target: ldm.models.autoencoder.AutoencoderKL
    params:
      embed_dim: 4
      monitor: val/rec_loss
      ddconfig:
        #attn_type: "vanilla-xformers"
        double_z: true
        z_channels: 4
        resolution: 256
        in_channels: 3
        out_ch: 3
        ch: 128
        ch_mult:
        - 1
        - 2
        - 4
        - 4
        num_res_blocks: 2
        attn_resolutions: []
        dropout: 0.0
      lossconfig:
        target: torch.nn.Identity

  cond_stage_config:
    target: ldm.modules.encoders.modules.OpenCLIPEmbedder
    params:
      freeze: False
      layer: "penultimate"
      version: "weights/laion2b_s32b_b79k/open_clip_pytorch_model.bin"
